import { StyleSheet} from "react-native";

export const GlobalStyles = StyleSheet.create({
  
  box1:{
        flex:0.1,
//    backgroundColor:'red',
        marginHorizontal:'2%',
        alignItems:'flex-start',
        position:'absolute',
        top:'15%',
        flexDirection:'row',
    }, 
    box2:{
      flex:0.1,
      width:'80%',
   // backgroundColor:'red',
      marginHorizontal:'2%',
      position:'absolute',
      top:'30%',
      alignItems:'center',
      flexDirection:'column',
  },
    box3:{
    flex:0.4,
    width:'100%',
//    backgroundColor:'red',
    justifyContent:'center',
    position:'absolute',
    bottom:'15%',
    alignContent:'center',
    alignItems:'center',
    flexDirection:'column',
}, 
  cont_reloj:{
        flex:1,
  //    backgroundColor:`blue`,
        flexDirection:'column',
        alignItems:'center',
        alignContent:'center',
        justifyContent:'center',
    },
    cont_relojB:{
        flex:0.4,
 //      backgroundColor:'yellow',
        flexDirection:'column',
        alignItems:'center',
        alignContent:'center',
        justifyContent:'center',
    },
    cont_relojC:{
      flex:1,
  //    backgroundColor:'yellow',
      marginBottom:'2%',
      flexDirection:'column',
      alignItems:'center',
      alignContent:'center',
      justifyContent:'center',
  },
    resultA:{
        flex:1,
        flexDirection:'row',
   //     backgroundColor:`green`,
        alignItems:'center',
        alignContent:'space-around',
        justifyContent:'center',
        opacity:1.70, 
        borderRadius:18, 
        width:'95%',
  },
  relojes:{
    width:'90%',
    borderRadius:1,
    borderWidth: 3,
    backgroundColor:'#FFF0AF',
    opacity:0.6,
    alignItems:'center',
    justifyContent:'center',
    borderBottomRightRadius:10,
    borderRadius:4,
    borderColor:'black',
    margin:7,
  },
  fondo: {
    flex:1,
    resizeMode:'cover',
    justifyContent:'center',
    alignItems:'center',
    
  },
 
  txBotones:{
    fontSize: 24,
    letterSpacing:5,
    textTransform:'capitalize',
    textShadowRadius:2,
    textShadowColor:'lightgrey',
  },
  txETA:{
    fontSize:24,
    textAlign:'center',
    textAlignVertical:'center',
    fontWeight:'700',
    backgroundColor:'#fff5ee',
    marginHorizontal:'8%',
    borderRadius:10,
    padding:5,
    borderWidth:3,
    borderColor:'black',
  },
  txFLEX:{
    fontSize:24,
    textAlign:'center',
    textAlignVertical:'center',
    fontWeight:'700',
    backgroundColor:'#fff5ee',
    marginHorizontal:'8%',
    opacity:1,
    borderRadius:10,
    padding:5,
    borderWidth:3,
    borderColor:'black',
  },
  ModalStyle:{
    backgroundColor:`#f8f8ff`,
    borderWidth:3,
    borderStyle:'solid',
    borderColor:'#708090',
    margin:'6%',
    borderRadius: 10,
    shadowColor:'black',
    shadowOffset:{
      width:0,
      height:2,  
    },
    padding:15,
    shadowOpacity:0.25,
    shadowRadius:4,
    elevation:5,

  }, 
  InfoTX:{
    flex:1,
    flexWrap:'wrap',
    maxWidth:'800%',
    fontSize:16,
    textAlign:'center',
  
  },
  InfoStyle:{
    flex:1,
    backgroundColor:`#f8f8ff`,
    borderWidth:3,
    justifyContent:'center',
    borderStyle:'solid',
    flexDirection:'row',
    borderColor:'#708090',
    margin:'1%',
    marginTop:'8%',
    borderRadius: 10,
    shadowColor:'black',
    shadowOffset:{
      width:0,
      height:2,  
    },
    padding:10,
    shadowOpacity:0.25,
    shadowRadius:4,
    elevation:5,

  },
  bandejasStyle:{
    flex:1,
    backgroundColor:`#f8f8ff`,
    borderWidth:3,
    justifyContent:'center',
    borderStyle:'solid',
    flexDirection:'row',
    borderColor:'#708090',
    alignContent:'center',
    alignItems:'center',
    margin:'1%',
    marginTop:'2%',
    borderRadius: 10,
    shadowColor:'black',
    shadowOffset:{
      width:0,
      height:2,  
    },
    padding:10,
    shadowOpacity:0.25,
    shadowRadius:4,
    elevation:5,
  },
  cartelesInfoViaticos:{
    flex:0.5,
    backgroundColor:`#f8f8ff`,
    borderWidth:3,
    justifyContent:'center',
    borderStyle:'solid',
    flexDirection:'row',
    borderColor:'#708090',
    alignContent:'center',
    alignItems:'center',
    margin:'1%',
    marginTop:'2%',
    borderRadius: 10,
    shadowColor:'black',
    shadowOffset:{
      width:0,
      height:2,  
    },
    padding:10,
    shadowOpacity:0.25,
    shadowRadius:4,
    elevation:5,

  },
  CloseModal:{
    width:'70%',
    marginHorizontal:'15%',
    marginVertical:'2%',
  },
  TextoFlex:{
    fontWeight:'bold',
    paddingHorizontal:'4%',
    fontSize:20,
  },
  TitleFlex:{
    textDecorationLine:'underline',
    paddingBottom:'0%',
    textAlign:'center',
    fontWeight:'900',
    fontSize:30,
  },
  Title: {
    color: 'white',
    fontSize: 48,
    marginTop:'50%',
    fontWeight: 'bold',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
   },
  view2:{
    opacity:0.7,
    borderColor:'black',
    borderWidth:2,
    justifyContent:'center',
    alignContent:'center',
    alignItems:'center',
    marginVertical:15,
    backgroundColor:'yellow',
    borderRadius:30,
    paddingHorizontal:10

  },
  tituloFlex:{ 
    borderWidth:1,
    borderColor:'white',
    color:'white',
    textAlign: 'center', 
    textAlignVertical: 'center',
    fontSize: 28, 
    textTransform:'uppercase', 
    padding:2,
    paddingVertical:8,
    borderRadius:20,
    marginHorizontal:8,
    marginTop:'6%',
    marginVertical:6,
    fontWeight:'bold',
    backgroundColor:`black`
  },
  tituloViaticos:{
    width:'95%', 
    borderWidth:3,
    borderColor:'black',
    color:'black',
    alignSelf:'center',
    backgroundColor:'white',
    textAlign: 'center', 
    textAlignVertical: 'center',
    fontSize: 26, 
    textTransform:'uppercase', 
    padding:2,
    paddingVertical:2,
    borderRadius:15,
    marginTop:'0.5%',
    marginVertical:2,
    fontWeight:'bold',
    textShadowColor: '#8b4513', // Color de la sombra del texto
    textShadowOffset: { width: 1.5, height: 1.5 }, // Desplazamiento de la sombra
    textShadowRadius: 1, // Radio de la sombra
  },
  sumaFlex:{
    color:'white',
    fontWeight:'bold',
    fontSize:28,
    borderColor:'white',
    borderWidth:2,
    padding:4,
    marginLeft:8,
    justifyContent:'center',
    alignContent:'center',
    alignItems:'center',
    backgroundColor:`black`,
    borderRadius:25,
    paddingHorizontal:10,
    marginVertical:8,
  
  
  },
  bandejasAEP:{
    color:'white',
    fontWeight:'bold',
    fontSize:18,
    borderColor:'white',
    borderWidth:2,
    padding:2,
    justifyContent:'flex-start',
    alignContent:'flex-start',
    alignItems:'flex-start',
    backgroundColor:`black`,
    borderBottomRightRadius:12,
    paddingHorizontal:8,
    marginTop:0,
    alignSelf: 'flex-start',
  },
  valorHr:{
    textAlign:'left',
    fontWeight:'bold',
    textTransform:'uppercase',
    marginVertical:8,
    color:'darkgreen',
    fontSize:28,
  
  },
  valor$:{
    textAlign:'left',
    fontWeight:'bold',
    textTransform:'uppercase',
    marginVertical:8,
    color:'darkgreen',
    fontSize:28,
  },
   contenedorPostas:{
    flex:1,
    width:400,
    height:400,
    borderWidth:2,
    borderColor:'black', 
    borderRadius:20 
  },
  contenedorViaticos:{
    flex: 1,
    width:'auto',
    backgroundColor:`#f0e68c`
  },
   modalViaticos:{
    textDecorationLine:'underline',
    paddingBottom:'0%',
    textAlign:'center',
    fontWeight:'900',
    fontSize:20,
    textTransform:'uppercase'
  },
   escalas:{
    textAlign:'left',
    fontWeight:'bold',
    textTransform:'uppercase',
    marginVertical:8,
    color:'black',
    fontSize:18,
  },
    valorEscalas$:{
    textAlign:'left',
    fontWeight:'bold',
    textTransform:'uppercase',
    color:'darkgreen',
    fontSize:18,
  
  }, 
  contadorBandejasAep:{
      color:'#000000',
      backgroundColor:`white`,
      fontWeight:'bold',
      fontSize:20,
  },
   totalBandejasAep:{
    color:'#000000',
    padding:3,
    borderRadius:12,
    backgroundColor:`#fff5ee`,
    fontWeight:'bold',
    fontSize:20,

  },
    totalAep$:{
    color:'white',
    fontWeight:'bold',
    fontSize:20,
    borderColor:'white',
    borderWidth:2,
    padding:2,
    justifyContent:'flex-start',
    alignContent:'flex-start',
    alignItems:'flex-start',
    backgroundColor:'black',
    borderBottomRightRadius:12,
    paddingHorizontal:8,
    alignSelf: 'flex-start',
}, 
totalPostas$:{
  color:'black',
  fontWeight:'bold',
  fontSize:20,
  borderColor:'black',
  borderWidth:2,
  padding:2,
  marginTop:2,
  justifyContent:'flex-start',
  alignContent:'flex-start',
  alignItems:'flex-start',
  backgroundColor:`#f0fff0`,
  borderBottomRightRadius:12,
  paddingHorizontal:8,
  alignSelf: 'flex-start',
  shadowOffset:{
    width:0,
    height:2,  
  },
  padding:10,
  shadowOpacity:0.25,
  shadowRadius:4,
  elevation:5,
},
totalViaticos:{
  color:'#000080',
  fontWeight:'bold',
  borderColor:'#000080',
  fontSize:22,
  textAlign:'center',
  borderWidth:2,
  marginTop:2,
  padding:2,
  borderBottomRightRadius:20,
  shadowColor:'red',
  backgroundColor:'#ffefd5',
  textShadowColor: 'white', // Color de la sombra del texto
  textShadowOffset: { width: 2, height: 3 }, // Desplazamiento de la sombra
  textShadowRadius: 3, // Radio de la sombra
}, 

fondoViaticos: {
  flex:1,
  resizeMode:'cover',
  alignContent:'flex-end',
  justifyContent:'space-between'
  
},
VContInferior: {
  opacity: 0.9,
  flexDirection: 'row',
  alignItems: 'flex-end', // Alinea el contenido en el extremo inferior
  marginHorizontal: 6,
//  borderWidth: 2,
//  borderColor: 'lime',
  marginBottom:60,
},
VInfIzq:{
//  borderColor:'blue',
//  borderWidth:2,
  width:'56%',
  marginRight:0,
  marginTop:2,
},
ContenedorInfo:{
  flex:0.55,
  justifyContent:'flex-start' , 
  opacity:0.80,
  marginTop:100,
  backgroundColor:`#f8f8ff`,
  borderWidth:3,
  padding:3,
  margin:10,
  borderRadius:10,
//  borderColor:'red',
},
contenedorInfoViaticos:{
  flex:0.8,
  justifyContent:'flex-start' , 
  opacity:0.80,
  marginTop:100,
  backgroundColor:`#f8f8ff`,
  borderWidth:3,
  padding:3,
  margin:10,
  borderRadius:10,
//  borderColor:'red',
},
  })